# Generated by Django 3.0.7 on 2020-06-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_number', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('invoice_name', models.CharField(max_length=256)),
                ('invoice_date', models.DateField()),
            ],
        ),
    ]
