# Generated by Django 3.0.7 on 2020-06-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_auto_20200611_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicehome',
            name='user',
        ),
    ]
