# Generated by Django 3.0.7 on 2020-06-12 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0007_auto_20200612_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceinfo',
            name='invoice_pdf',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_app.InvoiceHome'),
        ),
    ]
